trigger:
  branches:
    include:
    - master
    - features/*
  paths:
    include:
    - src/NCNEPortal/*
    - src/Databases/NCNEWorkflowDatabase.EF/*
    - src/Common*
    - src/HpdDatabase.EF/*    

stages:
- stage: Build
  jobs:
    - job: RestoreBuildAndDeploy
      pool: "UKHO Windows 2019"
      
      workspace:
          clean: all

      steps:

      - task: UseDotNet@2
        displayName: 'Use .NET Core sdk'
        inputs:
          packageType: sdk
          version: 3.1.x
          installationPath: $(Agent.ToolsDirectory)\\dotnet
          
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '$(Build.SourcesDirectory)\\src\\ncneportal\\ncneportal.csproj'
          feedsToUse: 'select'
        displayName: 'dotnet restore ncneportal'
    
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '$(Build.SourcesDirectory)\\src\\ncneportal\\ncneportal.csproj'
        displayName: 'dotnet build ncneportal'
  
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '$(Build.SourcesDirectory)\\src\\NCNEPortal.UnitTests\\ncneportal.unittests.csproj'
          feedsToUse: 'select'
        displayName: 'dotnet restore ncneportal tests'
  
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '$(Build.SourcesDirectory)\\src\\NCNEPortal.UnitTests\\ncneportal.unittests.csproj'
        displayName: 'dotnet build ncneportal tests'
  
      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: '$(Build.SourcesDirectory)\\src\\NCNEPortal.UnitTests\\ncneportal.unittests.csproj'
          # Add back in once Razor component is removed or reworked
          # arguments: -c $(BuildConfiguration) --collect:"XPlat Code Coverage" -s $(Build.SourcesDirectory)\\src\\NCNEPortal.UnitTests\\CodeCoverage.runsettings
        displayName: 'dotnet test ncneportal tests'

      # Add back in once Razor component is removed or reworked 
      # - task: DotNetCoreCLI@2
      #   inputs:
      #     command: custom
      #     custom: tool
      #     arguments: install --tool-path . dotnet-reportgenerator-globaltool
      #   displayName: Install ReportGenerator tool

      # - script: reportgenerator -reports:$(Agent.TempDirectory)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/coverlet/reports -reporttypes:"Cobertura"
      #   displayName: Create reports
  
      # - task: PublishCodeCoverageResults@1
      #   displayName: 'Publish code coverage'
      #   inputs:
      #     codeCoverageTool: Cobertura
      #     summaryFileLocation: $(Build.SourcesDirectory)\coverlet\reports\Cobertura.xml

      # - task: DotNetCoreCLI@2
      #   inputs:
      #     command: 'restore'
      #     projects: '$(Build.SourcesDirectory)\\src\\Portal.TestAutomation.Specs\\Portal.TestAutomation.Specs.csproj'
      #     feedsToUse: 'select'
      #   displayName: 'dotnet restore portalspecs'
  
      # - task: DotNetCoreCLI@2
      #   inputs:
      #     command: 'build'
      #     projects: '$(Build.SourcesDirectory)\\src\\Portal.TestAutomation.Specs\\Portal.TestAutomation.Specs.csproj'
      #   displayName: 'dotnet build portalspecs'
  
      # - task: CmdLine@2
      #   inputs:
      #     script: 'choco install pickles'
      #   displayName: Install Pickles
  
      # - task: CmdLine@2
      #   inputs:
      #     script: 'pickles --feature-directory=$(System.DefaultWorkingDirectory)\\src\\Portal.TestAutomation.Specs --output-directory=$(System.DefaultWorkingDirectory)\\src\\Pickles.GeneratedDocumentation --system-under-test-name="Task Manager - Portal" --documentation-format=dhtml'
      #   displayName: Generate Pickles Documentation
  
      # - task: PublishBuildArtifacts@1
      #   inputs:
      #     PathtoPublish: '$(System.DefaultWorkingDirectory)\src\Pickles.GeneratedDocumentation'
      #     ArtifactName: 'drop'
      #     publishLocation: 'Container'
      #   displayName: Publish Pickles Artifact
  
      # - task: AzureFileCopy@3
      #   inputs:
      #     SourcePath: '$(System.DefaultWorkingDirectory)\src\Pickles.GeneratedDocumentation'
      #     azureSubscription: 'TestEngineering-Live'
      #     Destination: 'AzureBlob'
      #     storage: '$(AzureStorageAccount)'
      #     ContainerName: '$web/$(Build.Repository.Name)'
      #   displayName: Publish Pickles Artifact to Azure Blob Storage
  
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: '$(Build.SourcesDirectory)\\src\\ncneportal\\ncneportal.csproj'
          zipAfterPublish: false
          arguments: '--output $(Build.ArtifactStagingDirectory)\\ncneportal'
        displayName: 'Publish ncneportal-project'
  
      # - task: DotNetCoreCLI@2
      #   inputs:
      #     command: 'publish'
      #     publishWebProjects: false
      #     projects: '$(Build.SourcesDirectory)\\src\\Portal.TestAutomation.Specs\\Portal.TestAutomation.Specs.csproj'
      #     zipAfterPublish: false
      #     arguments: '--output $(Build.ArtifactStagingDirectory)\\Specs'
      #   displayName: 'Publish specs-project'
  
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)\\ncneportal'
          ArtifactName: 'ncneportal'
          publishLocation: 'Container'
        displayName: 'Publish ncneportal Artifact'
  
      # - task: PublishBuildArtifacts@1
      #   inputs:
      #     PathtoPublish: '$(Build.ArtifactStagingDirectory)\\specs'
      #     ArtifactName: 'specs'
      #     publishLocation: 'Container'
      #   displayName: 'Publish specs Artifact'

# - stage: DependencyCheck
#   dependsOn: Build
#   jobs:
#     - job: DependencyCheck
#       pool: NautilusBuild

#       steps:
#       - task: UseDotNet@2
#         displayName: 'Use .NET Core 2.2.x SDK'
#         inputs:
#           packageType: sdk
#           version: 2.1.x
#           installationPath: $(Agent.ToolsDirectory)\\dotnet

#       - task: UseDotNet@2
#         displayName: 'Use .NET Core 3.1.x SDK'
#         inputs:
#           packageType: sdk
#           version: 3.1.x
#           installationPath: $(Agent.ToolsDirectory)\\dotnet

#       - task: DotNetCoreCLI@2
#         inputs:
#           command: publish
#           arguments: "--configuration $(BuildConfiguration) --output $(System.DefaultWorkingDirectory)/publish_output"
#           projects: "**/ncneportal.csproj"
#           publishWebProjects: false
#           modifyOutputPath: false
#           zipAfterPublish: false

#       - task: CmdLine@2
#         inputs:
#           script: 'dependency-check --project "ncneportal - $(Build.SourceBranchName)" --scan "$(System.DefaultWorkingDirectory)/publish_output" --out "$(Build.SourcesDirectory)\DCReport" --suppression $(Build.SourcesDirectory)\NVDSuppressions.xml"'
#         displayName: "Run NVD Checker"

#       - task: PublishPipelineArtifact@1
#         inputs:
#           targetPath: '$(Build.SourcesDirectory)\DCReport'
#           artifact: "NVD report"
#           publishLocation: "pipeline"

#       - task: PowerShell@2
#         displayName: "Fail build if depdency checker has vulnerabilities"
#         inputs:
#           targetType: inline
#           script: Invoke-VulnerabilityCheck -ReportLocation $(Build.SourcesDirectory)\DCReport\*

- stage: DeployDev
  dependsOn: Build
  jobs:    
    - deployment: DeployNCNEPortalWebsiteDev
      displayName: Deploy ncneportal website
      pool: "UKHO Ubuntu 1804"
        # creates an environment if it doesn't exist
      environment: 'TaskmanagerDev'
      strategy:
        # default deployment strategy, more coming...
        runOnce:
          deploy:
            steps:
              - task: AzureRmWebAppDeployment@4
                displayName: 'Azure App Service Deploy'
                inputs:
                  azureSubscription: 'TaskmanagerDev'
                  WebAppName: 'taskmanager-dev-web-ncneportal'
                  packageForLinux: '$(Pipeline.Workspace)/ncneportal/ncneportal'

    # - job: RunAutomatedTests
    #   dependsOn: DeployNCNEPortalWebsiteDev
    #   pool:
    #       NautilusBuild
    #   steps:
    #     - task: PowerShell@2
    #       inputs:
    #         targetType: 'inline'
    #         script: |
    #           Install-Module -Name "UKHO.ChromeDriver.BinarySync"  -Repository "ukho.psgallery"
    #           Update-ChromeDriver -ChromeDriverDownloads \\mgmt.local\dfs\DML-SW-Engineering\Chrome\ChromeDriver -IncludeBeta

    #     - task: DownloadBuildArtifacts@0
    #       displayName: 'Download Build Artifacts'
    #       inputs:
    #         buildType: 'current'
    #         downloadType: 'specific'
    #         downloadPath: '$(System.ArtifactsDirectory)' 

    #     - task: AzureCLI@1
    #       inputs:
    #         azureSubscription: 'TM2-Dev'
    #         scriptLocation: 'inlineScript'
    #         inlineScript: 'call dotnet vstest $(System.ArtifactsDirectory)\specs\Portal.TestAutomation.Specs\Portal.TestAutomation.Specs.dll --logger:trx'
    #       displayName: 'Run SpecFlow tests'

    #     - task: PublishTestResults@2
    #       inputs:
    #         testResultsFiles: '**/*.trx'
    #         testResultsFormat: 'VSTest'

- stage: DeployUAT
  dependsOn: Build
  jobs:    
    - deployment: DeployNCNEPortalWebsiteUAT
      displayName: Deploy ncneportal website
      pool: "UKHO Ubuntu 1804"
        # creates an environment if it doesn't exist
      environment: 'TaskmanagerUAT'
      strategy:
        # default deployment strategy, more coming...
        runOnce:
          deploy:
            steps:
              - task: AzureRmWebAppDeployment@4
                displayName: 'Azure App Service Deploy'
                inputs:
                  azureSubscription: 'TaskmanagerUAT-SC'
                  WebAppName: 'taskmanager-uat-web-ncneportal'
                  packageForLinux: '$(Pipeline.Workspace)/ncneportal/ncneportal'

- stage: DeployPre
  dependsOn: Build
  jobs:    
    - deployment: DeployNCNEPortalWebsitePre
      displayName: Deploy ncneportal website
      pool: "UKHO Ubuntu 1804"
        # creates an environment if it doesn't exist
      environment: 'TaskmanagerPre'
      strategy:
        # default deployment strategy, more coming...
        runOnce:
          deploy:
            steps:
              - task: AzureRmWebAppDeployment@4
                displayName: 'Azure App Service Deploy'
                inputs:
                  azureSubscription: 'TaskmanagerPre-SC'
                  WebAppName: 'taskmanager-pre-web-ncneportal'
                  packageForLinux: '$(Pipeline.Workspace)/ncneportal/ncneportal'
