trigger:
  branches:
    include:
    - bentest/*
  paths:
    include:
    - src/Portal*
    - src/Databases/WorkflowDatabase.EF/*
    - src/Common*
    - src/HpdDatabase.EF/*  

variables:
  MSBUILDSINGLELOADCONTEXT: '1'
  # This is a workaround for an issue building SpecFlow projects using the .NET Core SDK 3.1.200 https://github.com/SpecFlowOSS/SpecFlow/issues/1912

stages:
- stage: Build
  jobs:
    - job: RestoreBuildAndDeploy
      pool: "UKHO Windows 2019"
      
      workspace:
          clean: all

      steps:

      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'

      - script: npm install -g alex

      - task: Npm@1
        inputs:
          command: custom
          customCommand: alex
        displayName: alex.js linter

