trigger:
  branches:
    include:
    - features/*
  paths:
    include:
    - src/Databases/WorkflowDatabase*

pr:
  branches:
    include:
    - master
  paths:
    include:
    - src/Databases/WorkflowDatabase*

stages:
- stage: Build
  jobs:
    - job: RestoreBuildAndDeploy
      pool: "UKHO Windows 2019"

      workspace:
          clean: all

      steps:
      - task: VSBuild@1
        inputs:
          solution: '$(Build.SourcesDirectory)\\src\\Databases\\WorkflowDatabase\\WorkflowDatabase.sqlproj'
          msbuildArgs: /t:Build;Publish /p:SqlPublishProfilePath=WorkflowDatabase.LocalDb.publish.xml
        displayName: 'Build WorkflowDatabase and publish to LocalDb'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: '$(Build.SourcesDirectory)\\src\\Databases\\WorkflowDatabase.Tests\\WorkflowDatabase.Tests.csproj'
        displayName: 'dotnet test LocalDb instance of database'

      - task: VSBuild@1
        inputs:
          solution: '$(Build.SourcesDirectory)\\src\\Databases\\WorkflowDatabase\\WorkflowDatabase.sqlproj'
        displayName: 'Build WorkflowDatabase Dacpac'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)\\src\\Databases\\WorkflowDatabase\\bin\\debug\\WorkflowDatabase.dacpac'
          ArtifactName: 'workflowdatabase'
          publishLocation: 'Container'
        displayName: 'Publish WorkflowDatabase'

- stage: DeployDev
  dependsOn: Build
  jobs:
    - deployment: DeployWorkflowDatabaseDev
      displayName: Deploy WorkflowDatabase
      pool: "NautilusRelease"
      environment: 'TaskmanagerDev'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: SqlAzureDacpacDeployment@1
                inputs:
                  AuthenticationType: aadAuthenticationPassword
                  azureSubscription: 'SharedServicesPre'
                  ServerName: '$(ServerNameDev)'
                  DatabaseName: '$(DatabaseNameDev)'
                  aadSqlUsername: '$(SQLUsernameDev)'
                  aadSqlPassword: '$(SQLPasswordDev)'
                  DacpacFile: '$(Pipeline.Workspace)/workflowdatabase/WorkflowDatabase.dacpac'

- stage: DeployUAT
  dependsOn: Build
  jobs:
    - deployment: DeployWorkflowDatabaseUAT
      displayName: Deploy WorkflowDatabase
      pool: "NautilusRelease"
      environment: 'TaskmanagerUAT'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: SqlAzureDacpacDeployment@1
                inputs:
                  AuthenticationType: aadAuthenticationPassword
                  azureSubscription: 'SharedServicesPre'
                  ServerName: '$(ServerNameUAT)'
                  DatabaseName: '$(DatabaseNameUAT)'
                  aadSqlUsername: '$(SQLUsernameUAT)'
                  aadSqlPassword: '$(SQLPasswordUAT)'
                  DacpacFile: '$(Pipeline.Workspace)/workflowdatabase/WorkflowDatabase.dacpac'

- stage: DeployPre
  dependsOn: Build
  jobs:
    - deployment: DeployWorkflowDatabasePre
      displayName: Deploy WorkflowDatabase
      pool: "NautilusRelease"
      environment: 'TaskmanagerPre'
      strategy:
        runOnce:
          deploy:
            steps:
              - task: SqlAzureDacpacDeployment@1
                inputs:
                  AuthenticationType: aadAuthenticationPassword
                  azureSubscription: 'SharedServicesPre'
                  ServerName: '$(ServerNamePre)'
                  DatabaseName: '$(DatabaseNamePre)'
                  aadSqlUsername: '$(SQLUsernamePre)'
                  aadSqlPassword: '$(SQLPasswordPre)'
                  DacpacFile: '$(Pipeline.Workspace)/workflowdatabase/WorkflowDatabase.dacpac'